// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day2.Models;

[Keyless]
public partial class Department
{
    public int? ID { get; set; }

    [StringLength(10)]
    public string Name { get; set; }

    [StringLength(10)]
    public string Location { get; set; }
}