// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Day2.Models;

public partial class student
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string? Name { get; set; }

    ////////////[JsonIgnore (Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? age { get; set; }

    [StringLength(10)]
    public string address { get; set; }

    ///////////[JsonIgnore]
    public int? deptid { get; set; }
}