// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day2.Models;

public partial class User
{
    [Column("First name")]
    [StringLength(10)]
    public string First_name { get; set; }

    [StringLength(10)]
    public string SecoundName { get; set; }

    [StringLength(10)]
    public string FamilyName { get; set; }

    public long? NationalId { get; set; }

    [StringLength(1000)]
    public string Email { get; set; }

    [StringLength(10)]
    public string PlaceOfBirth { get; set; }

    [StringLength(10)]
    public string Nationality { get; set; }

    [Key]
    public int ID { get; set; }
}